FROM microsoft/dotnet-nightly:2.1-runtime-alpine
#FROM microsoft/dotnet:2.1-sdk-alpine AS build

RUN apk update && \
    apk upgrade --available && \
    apk add --update --no-cache libc6-compat \
    apk 

## 
# Tried Alpine but no joy .. need to investigate

WORKDIR /src 
COPY target/ ./
ENTRYPOINT [ "dotnet","www.dll" ]


